#pragma once
#include "config.h"
#include "latest_snapshot.h"

// Render owns Config. Unity owns its copy; no game call holds the UI gate.
namespace RuntimeSettings {
struct Values {
    bool bSaitama=false,bExplosiveMods=false,bContactExpl=false;
    float fNadeTime=2,fExplRadius=8,fExplDamage=500;
    int iGrantItem=0,iGrantRequest=0,iItemAmount=1;
    bool bZombieHeadDot=false;
    decltype(Config::bNoClip) bNoClip = {};
    decltype(Config::fNoClipSpeed) fNoClipSpeed = {};
    decltype(Config::iItemFilter0) iItemFilter0 = {};
    decltype(Config::iItemFilter1) iItemFilter1 = {};
    decltype(Config::iItemFilter2) iItemFilter2 = {};
    decltype(Config::iItemFilter3) iItemFilter3 = {};
    decltype(Config::iPoiFilter) iPoiFilter = {};
    decltype(Config::bPoiGraves) bPoiGraves = {};
    decltype(Config::bPoiPlayers) bPoiPlayers = {};
    decltype(Config::bEnemyMagnet) bEnemyMagnet = {};
    decltype(Config::fMagnetRadius) fMagnetRadius = {};
    decltype(Config::bAllyEsp) bAllyEsp = {};
    decltype(Config::iMagnetTargets) iMagnetTargets = {};
    int iMagnetArrangement=0;
    int iPyreSelection=0,iPyreRequest=0;
    bool bChams=false, bSilhouette=false;
    decltype(Config::bPoiWave) bPoiWave = {};
    int chamsVisible=0,chamsHidden=0;
    decltype(Config::fMagnetFront) fMagnetFront={};
    decltype(Config::fMagnetBoss) fMagnetBoss={};
    decltype(Config::bMagnetFreeze) bMagnetFreeze={};
    decltype(Config::bItemMagnet) bItemMagnet={};
    decltype(Config::fItemMagnetRadius) fItemMagnetRadius={};
    decltype(Config::iItemMagnetType) iItemMagnetType={};
    decltype(Config::iLootFilter0) iLootFilter0={};
    decltype(Config::iLootFilter1) iLootFilter1={};
    decltype(Config::iLootFilter2) iLootFilter2={};
    decltype(Config::iLootFilter3) iLootFilter3={};
    decltype(Config::iMagnetDestination) iMagnetDestination={};
    decltype(Config::bLootWholeMap) bLootWholeMap={};
    float viewportWidth=1920, viewportHeight=1080;
    decltype(Config::b360Mode) b360Mode = {};
    decltype(Config::bAimbot) bAimbot = {};
    decltype(Config::bAutoAim) bAutoAim = {};
    decltype(Config::bAutoFire) bAutoFire = {};
    decltype(Config::bDebugOverlay) bDebugOverlay = {};
    decltype(Config::bFastKnife) bFastKnife = {};
    decltype(Config::bFullAuto) bFullAuto = {};
    decltype(Config::bGodMode) bGodMode = {};
    decltype(Config::bInfAmmo) bInfAmmo = {};
    decltype(Config::bInfItems) bInfItems = {};
    decltype(Config::bInfMoney) bInfMoney = {};
    decltype(Config::bInfStamina) bInfStamina = {};
    decltype(Config::bInstantReload) bInstantReload = {};
    decltype(Config::bItemAmmo) bItemAmmo = {};
    decltype(Config::bItemEsp) bItemEsp = {};
    decltype(Config::bItemRare) bItemRare = {};
    decltype(Config::bItemSupply) bItemSupply = {};
    decltype(Config::bItemWeapons) bItemWeapons = {};
    decltype(Config::bLimitFov) bLimitFov = {};
    decltype(Config::bMenuOpen) bMenuOpen = {};
    decltype(Config::bNoRecoil) bNoRecoil = {};
    decltype(Config::bNoSpread) bNoSpread = {};
    decltype(Config::bNoSway) bNoSway = {};
    decltype(Config::bPoiBench) bPoiBench = {};
    decltype(Config::bPoiBoss) bPoiBoss = {};
    decltype(Config::bPoiEsp) bPoiEsp = {};
    decltype(Config::bPoiFire) bPoiFire = {};
    decltype(Config::bPoiHeli) bPoiHeli = {};
    decltype(Config::bPoiLootFix) bPoiLootFix = {};
    decltype(Config::bPoiMission) bPoiMission = {};
    decltype(Config::bPoiRespawn) bPoiRespawn = {};
    decltype(Config::bPoiShop) bPoiShop = {};
    decltype(Config::bRapidFire) bRapidFire = {};
    decltype(Config::bRollSpeed) bRollSpeed = {};
    decltype(Config::bSilentAim) bSilentAim = {};
    decltype(Config::bSpeedHack) bSpeedHack = {};
    decltype(Config::bSuperJump) bSuperJump = {};
    decltype(Config::bTightAim) bTightAim = {};
    decltype(Config::bTriggerbot) bTriggerbot = {};
    decltype(Config::bUnlockLoadout) bUnlockLoadout = {};
    decltype(Config::bUnlockSlots) bUnlockSlots = {};
    decltype(Config::bZombieEsp) bZombieEsp = {};
    decltype(Config::bZombieSkeleton) bZombieSkeleton = {};
    decltype(Config::fAimDistance) fAimDistance = {};
    decltype(Config::fEspDistance) fEspDistance = {};
    decltype(Config::fFovAngle) fFovAngle = {};
    decltype(Config::fItemRadius) fItemRadius = {};
    decltype(Config::fPoiRadius) fPoiRadius = {};
    decltype(Config::fJumpMult) fJumpMult = {};
    decltype(Config::fKnifeMult) fKnifeMult = {};
    decltype(Config::fRapidMult) fRapidMult = {};
    decltype(Config::fRollMult) fRollMult = {};
    decltype(Config::fSmoothing) fSmoothing = {};
    decltype(Config::fSpeedMult) fSpeedMult = {};
    decltype(Config::iAimBone) iAimBone = {};
    decltype(Config::iAimKey) iAimKey = {};
    decltype(Config::iAimMode) iAimMode = {};
    decltype(Config::iAimPriority) iAimPriority = {};
    decltype(Config::iZombieBox) iZombieBox = {};
};
inline Values Capture(float width,float height) {
    Values values;
    values.bNoClip=Config::bNoClip;
    values.bSaitama=Config::bSaitama;values.bExplosiveMods=Config::bExplosiveMods;values.bContactExpl=Config::bContactExpl;
    values.fNadeTime=Config::fNadeTime;values.fExplRadius=Config::fExplRadius;values.fExplDamage=Config::fExplDamage;
    values.iGrantItem=Config::iGrantItem;values.iGrantRequest=Config::iGrantRequest;values.iItemAmount=Config::iItemAmount; values.fNoClipSpeed=Config::fNoClipSpeed;
    values.iItemFilter0=Config::iItemFilter0;
    values.iItemFilter1=Config::iItemFilter1;
    values.iItemFilter2=Config::iItemFilter2;
    values.iItemFilter3=Config::iItemFilter3;
    values.iPoiFilter=-1; // Categories are the sole source of POI filtering.
    values.bPoiGraves=Config::bPoiGraves;
    values.bPoiPlayers=Config::bPoiPlayers;
    values.bEnemyMagnet=Config::bEnemyMagnet;
    values.fMagnetRadius=Config::fMagnetRadius;
    values.bAllyEsp=Config::bAllyEsp; values.iMagnetTargets=Config::iMagnetTargets;
    values.iMagnetArrangement=Config::iMagnetArrangement;
    values.iPyreSelection=Config::iPyreSelection;values.iPyreRequest=Config::iPyreRequest;
    values.bChams=Config::bChams; values.bSilhouette=Config::bSilhouette;
    values.bPoiWave=Config::bPoiWave;
    auto pack=[](const float* c){unsigned result=0;for(int i=0;i<4;++i){float value=c[i];if(!(value>=0))value=0;if(value>1)value=1;result|=static_cast<unsigned>(value*255)<<(i*8);}return static_cast<int>(result);};
    values.chamsVisible=pack(Config::colChamsVis);values.chamsHidden=pack(Config::colChamsInv);
    values.fMagnetFront=Config::fMagnetFront;values.fMagnetBoss=Config::fMagnetBoss;
    values.bMagnetFreeze=Config::bMagnetFreeze;
    values.bItemMagnet=Config::bItemMagnet;
    values.fItemMagnetRadius=Config::fItemMagnetRadius;
    values.iItemMagnetType=Config::iItemMagnetType;
    values.iLootFilter0=Config::iLootFilter0;
    values.iLootFilter1=Config::iLootFilter1;
    values.iLootFilter2=Config::iLootFilter2;
    values.iLootFilter3=Config::iLootFilter3;
    values.iMagnetDestination=Config::iMagnetDestination;
    values.bLootWholeMap=Config::bLootWholeMap;
    values.viewportWidth=width; values.viewportHeight=height;
    values.b360Mode=Config::b360Mode;
    values.bAimbot=Config::bAimbot;
    values.bAutoAim=Config::bAutoAim;
    values.bAutoFire=Config::bAutoFire;
    values.bDebugOverlay=Config::bDebugOverlay;
    values.bFastKnife=Config::bFastKnife;
    values.bFullAuto=Config::bFullAuto;
    values.bGodMode=Config::bGodMode;
    values.bInfAmmo=Config::bInfAmmo;
    values.bInfItems=Config::bInfItems;
    values.bInfMoney=Config::bInfMoney;
    values.bInfStamina=Config::bInfStamina;
    values.bInstantReload=Config::bInstantReload;
    values.bItemAmmo=Config::bItemAmmo;
    values.bItemEsp=Config::bItemEsp;
    values.bItemRare=Config::bItemRare;
    values.bItemSupply=Config::bItemSupply;
    values.bItemWeapons=Config::bItemWeapons;
    values.bLimitFov=!Config::b360Mode;
    values.bMenuOpen=Config::bMenuOpen;
    values.bNoRecoil=Config::bNoRecoil;
    values.bNoSpread=Config::bNoSpread;
    values.bNoSway=Config::bNoSway;
    values.bPoiBench=Config::bPoiBench;
    values.bPoiBoss=Config::bPoiBoss;
    values.bPoiEsp=Config::bPoiEsp;
    values.bPoiFire=Config::bPoiFire;
    values.bPoiHeli=Config::bPoiHeli;
    values.bPoiLootFix=Config::bPoiLootFix;
    values.bPoiMission=Config::bPoiMission;
    values.bPoiRespawn=Config::bPoiRespawn;
    values.bPoiShop=Config::bPoiShop;
    values.bRapidFire=Config::bRapidFire;
    values.bRollSpeed=Config::bRollSpeed;
    values.bSilentAim=Config::bSilentAim;
    values.bSpeedHack=Config::bSpeedHack;
    values.bSuperJump=Config::bSuperJump;
    values.bTightAim=Config::bTightAim;
    values.bTriggerbot=Config::bTriggerbot;
    values.bUnlockLoadout=Config::bUnlockLoadout;
    values.bUnlockSlots=Config::bUnlockSlots;
    values.bZombieEsp=Config::bZombieEsp;
    values.bZombieSkeleton=Config::bZombieSkeleton;
    values.bZombieHeadDot=Config::bZombieHeadDot;
    values.fAimDistance=Config::fAimDistance;
    values.fEspDistance=Config::fEspDistance;
    values.fFovAngle=Config::fFovAngle;
    values.fItemRadius=Config::fItemRadius;
    values.fPoiRadius=Config::fPoiRadius;
    values.fJumpMult=Config::fJumpMult;
    values.fKnifeMult=Config::fKnifeMult;
    values.fRapidMult=Config::fRapidMult;
    values.fRollMult=Config::fRollMult;
    values.fSmoothing=Config::fSmoothing;
    values.fSpeedMult=Config::fSpeedMult;
    values.iAimBone=Config::iAimBone;
    values.iAimKey=Config::iAimKey;
    values.iAimMode=Config::iAimMode;
    values.iAimPriority=Config::iAimPriority;
    values.iZombieBox=Config::iZombieBox;
    return values;
}
class Channel {
    LatestSnapshot<Values> snapshot;
public:
    void Publish(const Values& values) { snapshot.Publish(values); }
    Values Read() { return snapshot.Read(); }
};
}
