"""Produce clean starter ZIPs. Personalized packages are generated by ZB2 Admin."""
from pathlib import Path
import hashlib
import json
import shutil
import zipfile
ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'dist/entrega'
bundles={
 'CLIENTE':('loader/ZB2Menu.exe','ZB2Menu.exe'),
 'EQUIPE':('admin/ZB2Admin.exe','ZB2Admin.exe')}
records={}
for group,(source,name) in bundles.items():
    folder=OUTPUT/group;folder.mkdir(parents=True,exist_ok=True)
    shutil.copyfile(ROOT/'dist'/source,folder/name)
    for stale in ('LEIA-ME.txt','AVISOS.txt'):
        path=folder/stale
        assert path.resolve().parent==folder.resolve()
        path.unlink(missing_ok=True)
    # Required third-party attributions are embedded and readable in app Credits.
    allowed=[name]
    archive=OUTPUT/(group+'.zip')
    with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as package:
        for file in allowed:package.write(folder/file,group+'/'+file)
    with zipfile.ZipFile(archive) as package:
        assert sorted(package.namelist())==sorted(group+'/'+item for item in allowed)
        assert package.testzip() is None
    records[group]={'zip':str(archive),'sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),'files':allowed}
(ROOT/'build/delivery-manifest.json').write_text(json.dumps(records,indent=2),encoding='utf-8')
print('CLIENTE.zip: somente o Menu inicial; use o Admin para gerar ZIP personalizado com licenca.')
print('EQUIPE.zip: somente o Admin inicial; use o Admin para gerar ZIP personalizado com autorizacao.')
